version: '3'
services:
  runtime:
    image: sahebdatta/runtime:v_0.1.0
    restart: always
    volumes:
      - runtime:/var/lib/runtime

  # Displays the results in a Grafana dashborad
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana

volumes:
  grafana:
  runtime: